### ISSUE TITLE
npm package broken?

### ISSUE THREAD

**Issue by pumano** [lordfuoco/vue-xlsx#2]
Looks like that package not possible to use, because you don't have index.js in root of npm package?

Also your examples in docs from local imports of files.

**Comment by nmezzopera** [comment]
@pumano Hi thank you for the issue! the examples are linked to locally compiled files to not use the unpkg version.

The actual DIST is not committed to github but present in npm and the package.json contains all the pointers for the types of builds:

```
  "main": "dist/vue-xlsx.cjs.js",
  "unpkg": "dist/vue-xlsx.umd.js",
  "module": "dist/vue-xlsx.es.js",
```

I use the library in few projects so I know that the esm version works, how did you try to use the library ?

**Comment by pumano** [comment]
sorry, my bad, just misspelling in import causes it: looks like I wrote vue-xslx and got error. But after I type proper name - all is OK.
