### ISSUE TITLE
Get collection value from xlsx-json component

### ISSUE THREAD

**Issue by twentiecker** [lordfuoco/vue-xlsx#23]
How to get value of {{ collection }} after converted by xlsx-json components? 

        <xlsx-json :sheet="selectedSheet">
          <template #default="{ collection }">
            <div>
              {{ collection }} 
            </div>
          </template>
        </xlsx-json>

Im trying to direct access on it, but it failed, can you help me how to access it?

**Comment by knufri** [comment]
Hello @twentiecker I needed also a little research on it. This works for me. You can use the `parsed` event from the xlsx-json component:

```
<xlsx-read :file="file">
  <xlsx-json @parsed="outputJson" />
</xlsx-read>
```
and then:
```
methods: {
    outputJson(event) {
      console.log(JSON.stringify(event))
    }
}
```
then you get the same json data like in the template collection. Hope this helps.

**Comment by twentiecker** [comment]
Thanks sir, its work. :)
you helped me so much...
