### ISSUE TITLE
read data from xls files as string

### ISSUE THREAD

**Issue by afoninartem** [lordfuoco/vue-xlsx#24]
Hello!
Are there any options to read all data from xls as string? 
I have a problem with date format.
Cell from xls file with data like `30.12.2020  12:22:00` turns into `44195.5152777778`.
How can i get this data as string or how to parse it as a date?

**Comment by jayeshtechextensor** [comment]
Hello !!

I am facing the same issue, can you please suggest a solution, we are stuck with this issue and can not move ahead. Thanks

**Comment by afoninartem** [comment]
> Hello !!
> 
> I am facing the same issue, can you please suggest a solution, we are stuck with this issue and can not move ahead. Thanks

Hello, jayeshhhh!
I solved this problem: 
`const excelDateToJSDate = (serial) => {
	const utc_days = Math.floor(serial - 25569);
	const utc_value = utc_days * 86400;
	const date_info = new Date(utc_value * 1000);

	const fractional_day = serial - Math.floor(serial) + 0.0000001;

	let total_seconds = Math.floor(86400 * fractional_day);

	const seconds = total_seconds % 60;

	total_seconds -= seconds;

	const hours = Math.floor(total_seconds / (60 * 60));
	const minutes = Math.floor(total_seconds / 60) % 60;

  return what you need =)
};`

**Comment by vxmio** [comment]
@afoninartem thanx. it's working for me!
what the this numbers`25569`? what does it mean?

**Comment by jayeshhhh** [comment]
Hello @afoninartem , 
Thanks for the reply

You mean I need to pass "44765.00011574074" this string in a serial variable?

> > Hello !!
> > I am facing the same issue, can you please suggest a solution, we are stuck with this issue and can not move ahead. Thanks
> 
> Hello, jayeshhhh! I solved this problem: `const excelDateToJSDate = (serial) => { const utc_days = Math.floor(serial - 25569); const utc_value = utc_days * 86400; const date_info = new Date(utc_value * 1000);
> 
> ```
> const fractional_day = serial - Math.floor(serial) + 0.0000001;
> 
> let total_seconds = Math.floor(86400 * fractional_day);
> 
> const seconds = total_seconds % 60;
> 
> total_seconds -= seconds;
> 
> const hours = Math.floor(total_seconds / (60 * 60));
> const minutes = Math.floor(total_seconds / 60) % 60;
> ```
> 
> return what you need =) };`

**Comment by afoninartem** [comment]
@webm0fe it's number of days gone from 1900 to 1970 plus 2 days. Don't ask why, it's just works and returns expected value instead of 25567.
